name: Build and Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Login in firebase
        run: |
          cd workspace/backend
          firebase deploy -m "build: Hosting build for branch ${GITHUB_REF##*/} - ${GITHUB_SHA::7}" --project madegod-school-project --token "${{ secrets.FIREBASE_TOKEN}}"
